export enum FLIGHT_TYPE {
  NONSTOP = 'NONSTOP',
  DIRECT = 'DIRECT',
  CONNECTING = 'CONNECTING',
}

export enum CABIN_CLASS {
  ECONOMY = 'ECONOMY',
  PREMIUM_ECONOMY = 'PREMIUM_ECONOMY',
  BUSINESS = 'BUSINESS',
  FIRST = 'FIRST',
}

export enum STATUS {
  SCHEDULED = 'SCHEDULED',
  BOARDING = 'BOARDING',
  DELAYED = 'DELAYED',
  DEPARTED = 'DEPARTED',
  IN_AIR = 'IN_AIR',
  LANDED = 'LANDED',
  CANCELLED = 'CANCELLED',
  DIVERTED = 'DIVERTED',
}
